public class Address {
    public void homeAddress() {
        string myName = 'Yusuf';
        system.debug('My name is: ' + myName);
        integer totalNumberOfMembersInYourFamily = 4;
        system.debug('My family member total number : ' + totalNumberOfMembersInYourFamily);
        string houseName = 'Unit';
        system.debug('The House Name: ' + houseName);
        string houseNumber = '5';
        system.debug('The house number: ' + houseNumber);
        String streetName = 'Orsmkirk';
        system.debug('The Street name: ' + streetName);
        string cityName = 'Brisbane';
        system.debug('The city name is: ' + cityName);
        string stateName = 'Queensland';
        system.debug('The State name is: ' + stateName);
        string stateISOCode = '3166-2:AU';
        system.debug('State ISO code is: ' + stateISOCode);
        string countryName = 'Australia';
        system.debug('The name of country is: ' + countryName);
        string countryISOCode = '3166-3: AU';
        system.debug('The country ISO code is: ' + countryISOCode);
        String zipCode = '4116';
        system.debug('Zip Code is: '+ zipCode);
        boolean  isThisYourCurrentHome= true;
        system.debug('Australia is my current home  ' + isThisYourCurrentHome);

    }
}

