Calculator cl=new Calculator();
system.debug('Adding two parameters is ' + cl.dynamicCalulationMethod(10, 6, 'ADDITION'));
system.debug('Taking away two parameters is ' + cl.dynamicCalulationMethod(90, 60, 'Subtraction'));
system.debug('Div two parameters is ' + cl.dynamicCalulationMethod(10, 67.5, 'DIVISION'));
system.debug('Mult two parameters is ' + cl.dynamicCalulationMethod(10, 67.5, 'MULTIPLICATION'));




